"""empty message

Revision ID: fbaba93d8f5f
Revises: 
Create Date: 2021-08-02 15:01:15.611092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaba93d8f5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('minutes_per_game', sa.Float(), nullable=True),
    sa.Column('ft_attempts', sa.Integer(), nullable=True),
    sa.Column('ft_percentage', sa.Float(), nullable=True),
    sa.Column('tp_attempts', sa.Integer(), nullable=True),
    sa.Column('tp_percentage', sa.Float(), nullable=True),
    sa.Column('th_attempts', sa.Integer(), nullable=True),
    sa.Column('th_percentage', sa.Float(), nullable=True),
    sa.Column('points_per_game', sa.Float(), nullable=True),
    sa.Column('rebounds_per_game', sa.Float(), nullable=True),
    sa.Column('assists_per_game', sa.Float(), nullable=True),
    sa.Column('steals_per_game', sa.Float(), nullable=True),
    sa.Column('blocks_per_game', sa.Float(), nullable=True),
    sa.Column('turnovers_per_game', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
